#!/bin/bash

#    10-help-text - print the help text associated with the distro
#    Copyright (C) 2022 Nitrux Latinoamericana S.C.
#
#    Authors: Uri Herrera <uri_herrera@nxos.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#####   -- Variables

dist=$(cat /etc/os-release | grep "PRETTY_NAME=*" | rev | cut -d '=' -f 1 | rev)
url=https://nxos.org/
vendor='Nitrux Latinoamericana S.C.'
fecha=$(date +%Y)

#####   --  Format

BOLD='\e[1m'
ITALIC='\e[3m'
UNDERLINE='\e[4m'
NF='\e[0m'

#####   -- Colors

BLUE='\033[0;34m'
WHITE='\033[1;37m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

#####   -- Message

echo ' ';
echo '                          =                  ';
echo '                          =     .            ';
echo '                          =     .:::         ';
echo '::+.      ....:......     =         :::      ';
echo '%+-#=  ..:    :-:    .    =            :::.  ';
echo '--#-=-- --    .:#---.     =            .=#%#=';
echo '- .**=#= :      *    .    =         :+#%%%#=.';
echo '-   -# =#.    --     .    =      :+%%%%*-.   ';
echo '        ..  ..  ....      =   -+%%%%*-       ';
echo '                          =-*%%%%+:          ';
echo '                          +%%#+:             ';
echo ' ';
echo ' ';
echo -e "$dist";
echo ' ';
echo -e "(c) $fecha Some Rights Reserved. Made by $vendor";
echo ' ';
